### ISSUE TITLE
Support for hic data

### ISSUE THREAD

**Issue by QianzhaoJ** [aryeelab/diffloop-paper#1]
Hi:
I think It‘s helpful tools to find the differential loop structure !
But whether it can be used to the differential loop structure calling by hic data ? I can generate the input file like ` the first three columns specify the position (chr:start:stop) of the first anchor, the second three columns specify the position (chr:start:stop) of the secnd anchor, the 7th column is “.” and the 8th column is the number of paired-end reads` .
Thanks in advance !
Qianzhao

**Comment by caleblareau** [comment]
So in principle, the same model can be applied so you're certainly welcome (and encouraged) to try 

However, some of the accessor functions may be better with a dedicated HiC package such as diffHiC (https://bioconductor.org/packages/release/bioc/html/diffHic.html)

**Comment by QianzhaoJ** [comment]
Thanks !

**Comment by QianzhaoJ** [comment]
Thanks !
